# PV for Model (LLM) Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s/model  # Ensure this directory exists

---
# PVC for Model (LLM) Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  volumeName: model-pv  # Binds directly to model-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# PV for Data (shared access)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s/data  # Ensure this directory exists

---
# PVC for Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  volumeName: data-pv  # Binds directly to data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
# PV for Mlflow Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s/mlflow  # Ensure this directory exists

---
# PVC for Mlflow Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  volumeName: mlflow-pv  # Binds directly to mlflow-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
