FROM python:3.10

RUN apt-get update && apt-get install -y wget
RUN pip install -U uv

WORKDIR /app

COPY requirements.txt .
RUN uv pip install --system -r requirements.txt

COPY convert.py .

EXPOSE 8000

ENTRYPOINT ["uvicorn","convert:app","--host","0.0.0.0","--port","8000"]