apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-frontend
  labels:
    app: data-processing-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing-frontend
  template:
    metadata:
      labels:
        app: data-processing-frontend
    spec:
      containers:
      - name: frontend
        image: wcr.s-kuber.io/mlflow-pipeline/data-processing-frontend:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: data-processing-frontend-service
spec:
  selector:
    app: data-processing-frontend
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: NodePort